#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
OBSCURA=$DIR/../bin/obscura
TEST_FILE=$DIR/gbc.sav
IMAGE_1=$DIR/../image-1.pgm

function cleanup {
  rm -f "$DIR"/../*.pgm
}

function fail {
  cleanup

  echo >&2 "Failed test '$test'"
  echo >&2
  echo >&2 "Output: $output"

  exit 1
}

test="obscura must exist to be under test."
command -v "$OBSCURA" >/dev/null 2>&1 || { echo >&2 "Could not find 'obscura'. You should probable run 'make'."; exit 1; }

test="It should show usage information when run without commands."
output=$($OBSCURA)

if [[ $output != *"Usage:"* ]]; then
  fail
fi

test="It should show error message when file does not exist."
output="$($OBSCURA 2>&1 file-that-does-not-exists.sav)"

if [[ $output != *"Error:"* ]]; then
  fail
fi

$OBSCURA 2>&1 "$TEST_FILE"

test="Extracted image should have correct (known) hash."
output=$(md5 -q "$IMAGE_1")

if [[ $output != "89b98df2f0ebc2148ed28341634bde91" ]]; then
  fail
fi

cleanup

echo "All tests passed!"
